#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require_relative 'lexer.rb'

class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 20)

def parse(string)
  parser = Parser.new
  parser.scan_str(string)
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     3,     4,     5 ]

racc_action_check = [
     0,     1,     4 ]

racc_action_pointer = [
    -7,     1,   nil,   nil,     2,   nil ]

racc_action_default = [
    -2,    -4,    -1,    -3,    -4,     6 ]

racc_goto_table = [
     1,     2 ]

racc_goto_check = [
     1,     2 ]

racc_goto_pointer = [
   nil,     0,     1 ]

racc_goto_default = [
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 9, :_reduce_none,
  0, 9, :_reduce_2,
  1, 10, :_reduce_3 ]

racc_reduce_n = 4

racc_shift_n = 6

racc_token_table = {
  false => 0,
  :error => 1,
  :UMINUS => 2,
  "*" => 3,
  "/" => 4,
  "+" => 5,
  "-" => 6,
  :TEXT => 7 }

racc_nt_base = 8

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "UMINUS",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "TEXT",
  "$start",
  "target",
  "char" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'parser.y', 9)
  def _reduce_2(val, _values)
     "" 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 11)
  def _reduce_3(val, _values)
     puts "HELLO U" 
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

end   # class Parser
