#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require_relative 'lexer.rb'

class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 26)

def parse(string)
  scan_setup(string)
  tokens = []
  while token = next_token
    tokens << token
  end
  tokens << [:END, nil]
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     4,     6,     7,    13,     9,    10,    11,    12,    14 ]

racc_action_check = [
     0,     0,     0,     8,     0,     0,     0,     1,    12 ]

racc_action_pointer = [
    -2,     7,   nil,   nil,   nil,   nil,   nil,   nil,    -2,   nil,
   nil,   nil,     8,   nil,   nil ]

racc_action_default = [
    -2,   -13,    -1,    -3,    -4,    -5,    -6,    -7,    -8,   -10,
   -11,   -12,   -13,    -9,    15 ]

racc_goto_table = [
     1,     2,     3,     5,     8 ]

racc_goto_check = [
     1,     2,     3,     4,     5 ]

racc_goto_pointer = [
   nil,     0,     1,     2,     3,     4 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 10, :_reduce_none,
  0, 10, :_reduce_none,
  1, 11, :_reduce_none,
  1, 11, :_reduce_none,
  1, 12, :_reduce_none,
  1, 12, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  2, 13, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none ]

racc_reduce_n = 13

racc_shift_n = 15

racc_token_table = {
  false => 0,
  :error => 1,
  :NEWLINE => 2,
  :COMMENT => 3,
  :SET_NOPARENT => 4,
  :GLOB => 5,
  :USERNAME => 6,
  :TEAMNAME => 7,
  :EMAIL => 8 }

racc_nt_base = 9

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "NEWLINE",
  "COMMENT",
  "SET_NOPARENT",
  "GLOB",
  "USERNAME",
  "TEAMNAME",
  "EMAIL",
  "$start",
  "target",
  "lines",
  "line",
  "directive",
  "identifier" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
